(intro_numpy_notebook)=
# Introduzione a Numpy

## Introduzione

In questo e nei successivi capitoli presenteremo alcuni strumenti che possono essere usati per l'analisi esplorativa dei dati in Python. Solitamente i dati psicologi sono contenuti in file di vario formato (.xlsx, .csv, .dat, ...) e, nella quasi totalità dei casi, hanno una forma tabulare, ovvero sono organizzati in righe e colonne. Una volta letto un file di dati in Python dobbiamo eseguire varie manipolazioni su di esso: estrarre una o più colonne, applicare operazioni aritmetiche sulle colonne, creare nuove colonne, calcolare le statistiche di interesse, visualizzare i dati. Per eseguire queste operazioni utilizzeremo tre moduli Python:

- Pandas per caricare e manipolare i dati,
- NumPy per i calcoli numerici,
- Matplotlib e Seaborn per visualizzare i dati.

In questo capitolo introdurremo NumPy.

## NumPy

NumPy è l'abbreviazione di Numerical Python: un'estensione del linguaggio pensata per
l'ottizzazione della gestione di grosse moli di dati, utilizzata principalmente in ambito
scientifico. Numpy consente di lavorare con vettori e matrici in maniera più efficiente e veloce di quanto non si possa fare con le liste e le liste di liste (matrici) di Python. Inoltre, Numpy aggiunge una serie di funzioni matematiche di base e la possibilità di generare numeri casuali. 


## Gli array nel modulo NumPy

In Python puro abbiamo a disposizione 

- oggetti numerici: interi e floating point,
- container: liste e dizionari.

Numpy fornisce un nuovo tipo di dato: un array N-dimensionale (ndarray). Il costrutto ndarray è una struttura dati omogenea (solo numeri interi, solo floats, ...) che può avere dimensioni qualunque. 

**Terminologia**

- Con size di un array intendiamo il numero di elementi presenti in un array;
- Con rank di un array si intende il numero di assi/dimensioni di un array;
- Con shape di un array intendiamo le dimensioni dell’array, cioè una tupla di interi
contenente il numero di elementi per ogni dimensione.

```{image} images/size_rank_shape.png
:height: 300px
:align: center
```

<br>

Il modo più semplice per creare un array è di convertire una lista Python. Per esempio, possiamo creare un array 1-D nel modo seguente:

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


Un array 2-D si crea nel modo seguente:

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


È possibile creare un array 1-D con la funzione `.arange`:

In [5]:
print(np.arange(2, 9, 2))

[2 4 6 8]


Solitamente si usa `.arange` per incrementi unitari:

In [7]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


Un'altra funzione molto utile è `.linspace`:

In [11]:
x = np.linspace(0, 10, num=20)
print(x)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


Fissati gli estremi (qui 0, 10) e il numero di elementi desiderati, `.linspace` si occupa di determinare in maniera automatica l'incremento.

## Dimensioni dell'array

Un array è una griglia di elementi che possono essere indicizzati in vari modi. Le dimensioni dell'array sono chiamate "assi". L'array `a` ha due assi:

In [17]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
a.ndim

2

Ci sono 3 array di 4 elementi ciascuno:

In [19]:
a.shape

(3, 4)

Ricordando che in Python gli indici inziano da 0, il primo elemento dell'array `a` è

In [20]:
print(a[0])

[1 2 3 4]


Gli indici funzionano come ci possiamo aspettare, ricordando che il primo indice fa riferimento alla lista di array e il secondo indice agli elementi all'interno di ciascun array:

In [25]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

Per array 1-D

In [26]:
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
x[0:5]

array([0.        , 0.52631579, 1.05263158, 1.57894737, 2.10526316])

## Operazioni sugli array

Possiamo applicare le normali operazioni aritmetiche sugli array *elemento per elemento*.

In [31]:
x = a[0]
print(x)

[1 2 3 4]


In [32]:
y = a[1]
print(y)

[5 6 7 8]


In [34]:
z = x + y
print(z)

[ 6  8 10 12]


In [35]:
print(x * y)

[ 5 12 21 32]


In [36]:
print(x / y)

[0.2        0.33333333 0.42857143 0.5       ]


## Broadcasting

È possibile eseguire un'operazione tra un array e un singolo numero (chiamata anche operazione tra un vettore e uno scalare) o tra array di due dimensioni diverse. Ad esempio

In [37]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
print(2 * a)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


NumPy capisce che la moltiplicazione deve essere eseguita in ogni cella. Questo concetto si chiama *broadcasting*.

## Altre operazioni sugli array 

Ci sono un numero enorme di funzioni predefinite in NumPy che calcolano automaticamente diverse quantità. Ad esempio:

- `mean()`: calcola la media di un vettore o matrice;
- `sum()`: calcola la somma di un vettore o matrice;
- `std()`: calcola la deviazione standard;
- `min()`: trova il minimo nel vettore o matrice;
- `max()`: trova il massimo;
- `ndim`: dimensione del vettore o matrice;
- `shape`: restituisce una tupla con la "forma" del vettore o matrice;
- `size`: restituisce la dimensione totale del vettore (=ndim) o della matrice;
- `dtype`: scrive il tipo numpy del dato;
- `zeros(num)`: scrive un vettore di num elementi inizializzati a zero;
- `arange(start,stop,step)`: genera un intervallo di valori (interi o reali, a seconda dei valori di start, ecc.) intervallati di step. Nota che i dati vengono generati nell'intervallo aperto [start,stop)!
- `linstep(start,stop,num)`: genera un intervallo di num valori interi o reali a partire da start fino a stop (incluso!);
- `astype(tipo)`: converte l'ndarray nel tipo specificato

Per esempio:

In [40]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [50]:
print([x.min(), x.max(), x.sum(), x.mean(), x.std()])

[1, 3, 6, 2.0, 0.816496580927726]


## Lavorare con formule matematiche

È facile implementare le formule matematiche sugli array. Consideriamo, ad esempio, la formula della deviazione standard:

$$
s = \sqrt{\sum_{i=1}^n\frac{(x_i - \bar{x})^2}{n}}
$$

L'implementazione su un array NumPy è la seguente:

In [57]:
np.sqrt(np.sum((x - np.mean(x))**2) / np.size(x))

0.816496580927726

Questa implementazione funziona nello stesso modo sia che `x` contenga 3 elementi (come nel caso presente) sia che `x` contenga migliaia di elementi.

## Watermark

In [ ]:
%load_ext watermark
%watermark -n -u -v -iv -w -p pytensor